[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cx-worker"
version = "0.1.0"
description = "Background CSV Import Worker Process for CX Platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cx-contracts",
    "cx-domain",
    "cx-db"
]
